package com.example.hp.readtwitter.Engine;

public enum ResponseCode {
    NO_NETWORK_CONNECTION,

    AUTHORIZATION_PASSED, AUTHORIZATION_ERROR,

    FIRST_DATA_RECIVED, FIRST_DATA_FETCHING, FIRST_DATA_CANNOT_FETCH,

    PREV_POSTS_FETCH, PREV_POSTS_RECIVED, FETCHING_PREV_POSTS_ERROR,

    NEW_POSTS_RECIVED, NEW_POSTS_NO_PRESENT, NEW_POSTS_RECIVED_ERROR
}