package com.example.hp.readtwitter.Engine;

public enum ResponseCode {
    NO_NETWORK_CONNECTION,

    AUTHORIZATION_ERROR, AUTHORIZATION_PASSED,

    FETCHING_DATA, CANNOT_FETCH_DATA, DATA_RECIVED,

    FETCH_PREV_POSTS, PREV_POSTS_RECIVED, FETCHING_PREV_POSTS_ERROR,

    NEW_POSTS_RECIVED, NEW_POSTS_NO_RECIVED, NEW_POSTS_RECIVED_ERROR
}